export const RULE_DEFINITIONS = {
    'document-title': {
        ruleName: 'Document is missing a descriptive title',
        impact: 'serious',
        wcagRefs: ['WCAG 2.4.2'],
        help: 'Add a meaningful <title> so assistive technology can identify the page.',
        helpUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/page-titled.html',
        whyItMatters: 'People using screen readers rely on page titles to understand context and navigate browser history.',
        suggestedFix: 'Add a unique <title> element that summarizes the page purpose.',
        codeExample: '<title>Pricing | Example Co</title>',
        userImpactBoost: 1.2,
    },
    'html-lang': {
        ruleName: 'HTML element is missing a lang attribute',
        impact: 'serious',
        wcagRefs: ['WCAG 3.1.1'],
        help: 'Set the document language on the <html> element.',
        helpUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/language-of-page.html',
        whyItMatters: 'Screen readers use page language to pick pronunciation rules and voices.',
        suggestedFix: 'Set <html lang="en"> or the correct page language.',
        codeExample: '<html lang="en">',
        userImpactBoost: 1.15,
    },
    'image-alt': {
        ruleName: 'Images missing alternative text',
        impact: 'serious',
        wcagRefs: ['WCAG 1.1.1'],
        help: 'Provide informative alt text for meaningful images.',
        helpUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/non-text-content.html',
        whyItMatters: 'Without alt text, screen reader users miss image meaning and context.',
        suggestedFix: 'Add concise alt text or use alt="" for decorative images.',
        codeExample: '<img src="team-photo.jpg" alt="The customer success team" />',
        userImpactBoost: 1.4,
    },
    'form-label': {
        ruleName: 'Form controls missing associated labels',
        impact: 'critical',
        wcagRefs: ['WCAG 1.3.1', 'WCAG 3.3.2', 'WCAG 4.1.2'],
        help: 'Associate every input, textarea, or select with a visible label.',
        helpUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions.html',
        whyItMatters: 'Unlabeled controls prevent assistive technology users from understanding what information is required.',
        suggestedFix: 'Use a <label for> that references the control id or add aria-label when no visible label is possible.',
        codeExample: '<label for="email">Email address</label><input id="email" type="email" />',
        userImpactBoost: 1.5,
    },
    'button-name': {
        ruleName: 'Buttons missing accessible names',
        impact: 'serious',
        wcagRefs: ['WCAG 4.1.2', 'WCAG 2.4.6'],
        help: 'Ensure buttons expose a discernible name via text, aria-label, or aria-labelledby.',
        helpUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/name-role-value.html',
        whyItMatters: 'Unnamed controls are announced ambiguously, making forms and dialogs unusable.',
        suggestedFix: 'Add button text or an aria-label that describes the action.',
        codeExample: '<button aria-label="Open search"></button>',
        userImpactBoost: 1.4,
    },
    'link-name': {
        ruleName: 'Links missing accessible names',
        impact: 'serious',
        wcagRefs: ['WCAG 2.4.4', 'WCAG 4.1.2'],
        help: 'Give links visible or programmatic text that describes their destination.',
        helpUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/link-purpose-in-context.html',
        whyItMatters: 'Ambiguous links make navigation lists difficult for screen reader and speech input users.',
        suggestedFix: 'Add descriptive anchor text or an aria-label.',
        codeExample: '<a href="/pricing">View pricing plans</a>',
        userImpactBoost: 1.3,
    },
    'heading-order': {
        ruleName: 'Heading structure may skip levels',
        impact: 'moderate',
        wcagRefs: ['WCAG 1.3.1', 'WCAG 2.4.6'],
        help: 'Use heading levels in a logical order to reflect the information hierarchy.',
        helpUrl: 'https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships.html',
        whyItMatters: 'Consistent headings help screen reader users skim and understand content structure.',
        suggestedFix: 'Avoid jumping from H1 to H3 or deeper unless an intermediate heading level exists.',
        codeExample: '<h1>Pricing</h1><h2>Standard plan</h2>',
        userImpactBoost: 1.05,
    },
};

export const IMPACT_WEIGHTS = {
    critical: 4,
    serious: 3,
    moderate: 2,
    minor: 1,
};
